services:
  - type: web
    name: nhatrothanhtam-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://nhatrothanhtam.netlify.app
      - key: COOKIE_SAMESITE
        value: none
      - key: COOKIE_SECURE
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: ADMIN_COOKIE_SECRET
        sync: false
